import type { Category, TransactionKind } from "./types";

export const marketCategories: Category[] = [
  { id: "inkomsten-onderneming", name: "Onderneming", parent: "Inkomen", kind: "inkomen" },
  { id: "uitkering-toeslagen", name: "Uitkering/toeslagen", parent: "Inkomen", kind: "inkomen" },
  { id: "belasting", name: "Belasting", parent: "Financien", kind: "vaste_last" },
  { id: "gemeentelijke-lasten", name: "Gemeente en waterschap", parent: "Wonen", kind: "vaste_last" },
  { id: "water", name: "Water", parent: "Wonen", kind: "vaste_last" },
  { id: "internet-telefonie", name: "Internet en telefonie", parent: "Wonen", kind: "vaste_last" },
  { id: "zorgverzekering", name: "Zorgverzekering", parent: "Verzekeringen", kind: "vaste_last" },
  { id: "schadeverzekering", name: "Schadeverzekeringen", parent: "Verzekeringen", kind: "vaste_last" },
  { id: "uitvaartverzekering", name: "Uitvaartverzekering", parent: "Verzekeringen", kind: "vaste_last" },
  { id: "auto-onderhoud", name: "Auto onderhoud", parent: "Vervoer", kind: "variabele_uitgave" },
  { id: "brandstof", name: "Brandstof", parent: "Vervoer", kind: "variabele_uitgave" },
  { id: "parkeren", name: "Parkeren", parent: "Vervoer", kind: "variabele_uitgave" },
  { id: "openbaar-vervoer", name: "Openbaar vervoer", parent: "Vervoer", kind: "variabele_uitgave" },
  { id: "kleding-sport", name: "Kleding en sport", parent: "Leven", kind: "variabele_uitgave" },
  { id: "huis-tuin", name: "Huis en tuin", parent: "Wonen", kind: "variabele_uitgave" },
  { id: "horeca", name: "Horeca", parent: "Leven", kind: "variabele_uitgave" },
  { id: "webwinkels", name: "Webwinkels", parent: "Leven", kind: "variabele_uitgave" },
  { id: "zorgkosten", name: "Zorgkosten", parent: "Gezondheid", kind: "variabele_uitgave" },
  { id: "abonnementen-media", name: "Abonnementen en media", parent: "Leven", kind: "vaste_last" },
  { id: "goede-doelen", name: "Goede doelen", parent: "Leven", kind: "vaste_last" },
  { id: "gezin", name: "Gezin", kind: "variabele_uitgave" },
  { id: "zakgeld", name: "Zakgeld", parent: "Gezin", kind: "variabele_uitgave" },
  { id: "kinderen-opleiding", name: "Kinderen en opleiding", parent: "Gezin", kind: "variabele_uitgave" },
  { id: "beleggen", name: "Beleggen", parent: "Financien", kind: "reservering" },
];

export interface MarketRule {
  id: string;
  pattern: string;
  categoryId: string;
  kind: TransactionKind;
  matchScope?: "counterparty" | "description" | "counter_account" | "counterparty_description" | "counterparty_counter_account" | "description_counter_account" | "all";
}

export const marketMappingRules: MarketRule[] = [
  rule("Vdmeer Consultancy", "inkomsten-onderneming", "inkomen"),
  rule("STICHTING TIMON", "salaris", "inkomen"),
  rule("Sociale Verzekeringsbank", "uitkering-toeslagen", "inkomen"),
  rule("Belastingdienst", "belasting", "vaste_last"),
  rule("BELASTINGDIENST", "belasting", "vaste_last"),
  rule("Coop Rabobank Hollandse IJssel UA", "wonen", "vaste_last"),
  rule("ENECO SERVICES", "energie", "vaste_last"),
  rule("GBLT", "gemeentelijke-lasten", "vaste_last"),
  rule("BSGR", "gemeentelijke-lasten", "vaste_last"),
  rule("VITENS", "water", "vaste_last"),
  rule("OASEN", "water", "vaste_last"),
  rule("KPN B.V.", "internet-telefonie", "vaste_last"),
  rule("KPN - Mobiel", "internet-telefonie", "vaste_last"),
  rule("Interpolis Zorgverzekeringen", "zorgverzekering", "vaste_last"),
  rule("Interpolis", "schadeverzekering", "vaste_last"),
  rule("Klaverblad", "schadeverzekering", "vaste_last"),
  rule("Allianz Direct", "schadeverzekering", "vaste_last"),
  rule("ANWB Verzekeren", "schadeverzekering", "vaste_last"),
  rule("OHRA Schadeverzekeringen", "schadeverzekering", "vaste_last"),
  rule("Monuta", "uitvaartverzekering", "vaste_last"),
  rule("Albert Heijn", "boodschappen", "variabele_uitgave"),
  rule("ALBERT HEIJN", "boodschappen", "variabele_uitgave"),
  rule("Jumbo", "boodschappen", "variabele_uitgave"),
  rule("BCK*Jumbo", "boodschappen", "variabele_uitgave"),
  rule("Slagerij", "boodschappen", "variabele_uitgave"),
  rule("BP ", "brandstof", "variabele_uitgave"),
  rule("Shell", "brandstof", "variabele_uitgave"),
  rule("Tango", "brandstof", "variabele_uitgave"),
  rule("Q-Park", "parkeren", "variabele_uitgave"),
  rule("Parking", "parkeren", "variabele_uitgave"),
  rule("Ticket for Ticket System Vakantiepark De Heigraaf", "parkeren", "variabele_uitgave"),
  rule("NS ", "openbaar-vervoer", "variabele_uitgave"),
  rule("OVPAY", "openbaar-vervoer", "variabele_uitgave"),
  rule("Profile Gouda", "auto-onderhoud", "variabele_uitgave"),
  rule("Rijschool", "kinderen-opleiding", "variabele_uitgave"),
  rule("NL45 RABO 0328 3865 37", "zakgeld", "variabele_uitgave", "counter_account"),
  rule("Decathlon", "kleding-sport", "variabele_uitgave"),
  rule("Daka", "kleding-sport", "variabele_uitgave"),
  rule("New Balance", "kleding-sport", "variabele_uitgave"),
  rule("Sporthaus", "kleding-sport", "variabele_uitgave"),
  rule("IKEA", "huis-tuin", "variabele_uitgave"),
  rule("Karwei", "huis-tuin", "variabele_uitgave"),
  rule("Coolblue", "huis-tuin", "variabele_uitgave"),
  rule("HEMA", "huis-tuin", "variabele_uitgave"),
  rule("bol.com", "webwinkels", "variabele_uitgave"),
  rule("BOLCOM", "webwinkels", "variabele_uitgave"),
  rule("Amazon", "webwinkels", "variabele_uitgave"),
  rule("PayPal", "webwinkels", "variabele_uitgave"),
  rule("Riverty", "webwinkels", "variabele_uitgave"),
  rule("Vinted", "webwinkels", "variabele_uitgave"),
  rule("Pannenkoekerie", "horeca", "variabele_uitgave"),
  rule("Social Deal", "horeca", "variabele_uitgave"),
  rule("t Zusje", "horeca", "variabele_uitgave"),
  rule("Camping", "vakantie", "reservering"),
  rule("SKILIFT", "vakantie", "reservering"),
  rule("Tandheelkundig", "zorgkosten", "variabele_uitgave"),
  rule("Pharmapets", "zorgkosten", "variabele_uitgave"),
  rule("Storytel", "abonnementen-media", "vaste_last"),
  rule("Ring LLC", "abonnementen-media", "vaste_last"),
  rule("Stichting Compassion", "goede-doelen", "vaste_last"),
  rule("Stichting Kinderen Kankervrij", "goede-doelen", "vaste_last"),
  rule("Mozaiek", "goede-doelen", "vaste_last"),
  rule("Flatex", "beleggen", "reservering"),
  rule("Rabobank Nederland", "bankkosten", "vaste_last"),
  rule("Rabo standaard", "bankkosten", "vaste_last"),
];

function rule(pattern: string, categoryId: string, kind: TransactionKind, matchScope?: MarketRule["matchScope"]): MarketRule {
  return {
    id: `market_${pattern.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "")}_${categoryId}`.slice(0, 96),
    pattern,
    categoryId,
    kind,
    matchScope,
  };
}
